### ISSUE TITLE
2DSaver does not work with TWN region

### ISSUE THREAD

**Issue by BBasilio2001** [zoogie/2DSaver#1]
I tried to use 2DSaver with my 2DS when trying to change my region to Taiwan (TWN) with CTRTransfer, however it redirects me to the same slider configuration check.

**Comment by OniHueAlloz** [comment]
> I tried to use 2DSaver with my 2DS when trying to change my region to Taiwan (TWN) with CTRTransfer, however it redirects me to the same slider configuration check.

Hey I've got a similar issue did you find any way to solve yours?

**Comment by BBasilio2001** [comment]
> Hey I've got a similar issue did you find any way to solve yours?

I managed to CTRTransfer back to USA (my stock region) and then CTRTransfer again to TWN region, the entire initial setup is skipped.
